pipeline:
  identifier: Build_harness_demo_1699371679099
  name: Build harness-demo
  orgIdentifier: default
  projectIdentifier: K8sdemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699371641847
        repoName: harness-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: githubjv
                    build:
                      type: branch
                      spec:
                        branch: main
                  description: harness
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo maven build
                      mvn -version
                      mvn clean install
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
